### ISSUE TITLE
pull docker shows error

### ISSUE THREAD

**Issue by xellosiris** [xychelsea/deepfacelab-docker#1]
error message:
Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

**Comment by xychelsea** [comment]
Sorry, wasn't around for this -- I'm updating soon! The approach to dpkg install will be different but the usability the same.

**Comment by xychelsea** [comment]
SEE NEW RELEASE (TESTING) https://github.com/xychelsea/deepfacelab-docker/releases/tag/v0.1.3
