### ISSUE TITLE
ModuleNotFoundError: No module named 'colorama'

### ISSUE THREAD

**Issue by seaniedan** [xychelsea/deepfacelab-docker#10]
I tear the cellophane off a shiny new Jupyter notebook, and run

`!cd ~/scripts && ./4.2_data_src_util_add_landmarks_debug_images.sh
`
It's feeling better, but I get:
```
Traceback (most recent call last):
  File "/usr/local/deepfacelab/main.py", line 6, in <module>
    from core.leras import nn
  File "/usr/local/deepfacelab/core/leras/__init__.py", line 1, in <module>
    from .nn import nn
  File "/usr/local/deepfacelab/core/leras/nn.py", line 26, in <module>
    from core.interact import interact as io
  File "/usr/local/deepfacelab/core/interact/__init__.py", line 1, in <module>
    from .interact import interact
  File "/usr/local/deepfacelab/core/interact/interact.py", line 8, in <module>
    import colorama
ModuleNotFoundError: No module named 'colorama'
```
Let me know if you'd like me to investigate further.

**Comment by seaniedan** [comment]
Update: successfully albeit temporarily installed colorama with a cheeky
`!conda install -yc anaconda colorama
`
Now I get:
`ModuleNotFoundError: No module named 'cv2'
`
Full text:
```
!cd ~/scripts && ./4_data_src_extract_faces_S3FD.sh

Traceback (most recent call last):
  File "/usr/local/deepfacelab/main.py", line 6, in <module>
    from core.leras import nn
  File "/usr/local/deepfacelab/core/leras/__init__.py", line 1, in <module>
    from .nn import nn
  File "/usr/local/deepfacelab/core/leras/nn.py", line 26, in <module>
    from core.interact import interact as io
  File "/usr/local/deepfacelab/core/interact/__init__.py", line 1, in <module>
    from .interact import interact
  File "/usr/local/deepfacelab/core/interact/interact.py", line 9, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

**Comment by seaniedan** [comment]
Update: 
I stopped and removed the old container
```
docker stop deepfacelab
docker image rm xychelsea/deepfacelab:v0.2-gpu-jupyter
docker pull xychelsea/deepfacelab:v0.2-gpu-jupyter
./start.sh
```
(which runs 

```
#!/bin/bash

DEEPFACELAB_NAME=deepfacelab
DEEPFACELAB_WORKSPACE=/mnt/data/ml/deepface/work/workspace
DEEPFACELAB_MOUNT=/usr/local/deepfacelab/workspace
DEEPFACELAB_PORT=8888

docker run \
	--detach \
	--gpus all \
	--interactive \
	--name $DEEPFACELAB_NAME \
	--publish $DEEPFACELAB_PORT:8888 \
	--rm \
	--tty \
	--volume $DEEPFACELAB_WORKSPACE:$DEEPFACELAB_MOUNT \
	xychelsea/deepfacelab:v0.2-gpu-jupyter \

sleep 5
docker exec -it $DEEPFACELAB_NAME jupyter notebook list
```
..and the error persists - running

`!cd ~/scripts && ./4.2_data_src_util_add_landmarks_debug_images.sh
`
results in 
`ModuleNotFoundError: No module named 'colorama'
`

**Comment by seaniedan** [comment]
I like the pip installs - I'd keep going with that for 
opencv-python \
...colorama can be installed with Anaconda as above.

**Comment by seaniedan** [comment]
hmmm....  installing opencv in this way is CPU only. To get CUDA support may require [compiling](https://www.pyimagesearch.com/2016/07/11/compiling-opencv-with-cuda-support/)  Still, one step at a time....

**Comment by xychelsea** [comment]
Ah -- sorry I haven't pushed latest yet

**Comment by xychelsea** [comment]
Pushed latest version of v0.2-gpu-jupyter -- its massive -- you can also view main on github to see whats going on for yourself

**Comment by seaniedan** [comment]
Yeah, I saw it was pushed 'yesterday' and got confused about timezones! Will try again!

**Comment by seaniedan** [comment]
Hiya Chelsea, getting there - the next one you're missing is the ol' numeric python, Numpy:

`!cd ~/scripts && ./4.2_data_src_util_add_landmarks_debug_images.sh
`gives me
```
Traceback (most recent call last):
  File "/usr/local/deepfacelab/main.py", line 6, in <module>
    from core.leras import nn
  File "/usr/local/deepfacelab/core/leras/__init__.py", line 1, in <module>
    from .nn import nn
  File "/usr/local/deepfacelab/core/leras/nn.py", line 25, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by seaniedan** [comment]
This is the original iperov [requirements.txt file](https://github.com/iperov/DeepFaceLab/blob/master/requirements-cuda.txt)... that's the CUDA one, if it helps at all (I know you're doing something slightly different here).

**Comment by xychelsea** [comment]
Thanks I am correcting tonight after I stream

**Comment by xychelsea** [comment]
Following up with this -- I cant tell if its working or not on my own end -- but everything says it does

**Comment by seaniedan** [comment]
Hi Chelsea, 
I've been caught up in other projects, and the files for this one are so BIG that my system runs out of space, so I need to delete everything else before I can come back to take a look. In the meantime, I am looking forward to see what you do with this.

**Comment by seaniedan** [comment]
Hi Chelsea, apologies for the delay. I moved to a new machine with a bit more space for these huge Docker images! :-D

I run
`docker pull xychelsea/deepfacelab:latest-gpu-jupyter` ..I get the notebook server running, open a new python notebook and run one of the repo's shell scripts:
`!cd ~/scripts && ./4.2_data_src_util_add_landmarks_debug_images.sh`
I get:

```
Traceback (most recent call last):
  File "/usr/local/deepfacelab/main.py", line 6, in <module>
    from core.leras import nn
  File "/usr/local/deepfacelab/core/leras/__init__.py", line 1, in <module>
    from .nn import nn
  File "/usr/local/deepfacelab/core/leras/nn.py", line 25, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```
How are you debugging from your end, I'm not sure why you can't see the errors? Maybe you can contact me directly and we can sort it out? I'm sean <at> danischevsky dot com. Drop me a line, I'm keen to get this working and happy to help.

**Comment by xychelsea** [comment]
The latest version v0.3 fixes all of these issues and is much more robustly tested. Closing this issue.

**Comment by seaniedan** [comment]
Hi Chelsea, with the latest version, 

`docker pull xychelsea/deepfacelab:latest-gpu-jupyter
`
I still get the same issue as above: 

```
Traceback (most recent call last):
  File "/usr/local/deepfacelab/main.py", line 6, in <module>
    from core.leras import nn
  File "/usr/local/deepfacelab/core/leras/__init__.py", line 1, in <module>
    from .nn import nn
  File "/usr/local/deepfacelab/core/leras/nn.py", line 25, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by seaniedan** [comment]
Still getting this issue after rebuilding the Docker container with: 
`docker build -t deepfacelab:latest-gpu-jupyter -f Dockerfile.nvidia-jupyter .
`
I get the same error as above: No module named 'numpy' - can you confirm that you don't see this error if you run the script in this way? 

Perhaps I'm misunderstanding something fundemental here about how to use these shell scripts - could you write a very short documentation on what do do after running the Docker image?

**Comment by seaniedan** [comment]
Another insight: if I enter the docker container using
`docker exec -i -t deepfacelab /bin/bash
`
I can run the scripts:
`cd scripts && ./4.2_data_src_sort.sh 
`

...I just can't use the Jupyter notebook as a tool, as if I do:
`import numpy 
`or 
`import colorama`
I get 'module not found' errors.

**Comment by LoopControl** [comment]
After playing with the `latest-gpu` image, I finally found the problem/fix:

1) Key thing is that when you run any file in `/scripts`, it first runs `/scripts/env.sh` first which is pointing to `python3.8` -- this is wrong since the installation process uses `python3.7` instead. Changing `env.sh` to use `python3.7` fixes most issues.

2) There seems to be an issue with one of the environment variables being missing -- `DFL_SRC`. The fix is to add `export DFL_SRC="$DEEPFACELAB_PATH"` to `env.sh`

I'm guessing another way to fix the first issue would be to do the docker build process using python 3.8 instead but I'll just keep going with the env.sh change.

My modified/fixed `/scripts/env.sh`:

```
#!/usr/bin/env bash
export DFL_PYTHON="python3.7"
export DFL_WORKSPACE="$DEEPFACELAB_WORKSPACE"
export DFL_SRC="$DEEPFACELAB_PATH"

if [ ! -d "$DFL_WORKSPACE" ]; then
    mkdir "$DFL_WORKSPACE"
    mkdir "$DFL_WORKSPACE/data_src"
    mkdir "$DFL_WORKSPACE/data_src/aligned"
    mkdir "$DFL_WORKSPACE/data_src/aligned_debug"
    mkdir "$DFL_WORKSPACE/data_dst"
    mkdir "$DFL_WORKSPACE/data_dst/aligned"
    mkdir "$DFL_WORKSPACE/data_dst/aligned_debug"
    mkdir "$DFL_WORKSPACE/model"
fi
```
