### ISSUE TITLE
chmod: cannot access '/usr/local/deepfacelab/scripts/*.sh': No such file or directory

### ISSUE THREAD

**Issue by seaniedan** [xychelsea/deepfacelab-docker#2]
Thank you for providing this repo. However, I've had no luck with it so far. 

I do:
git clone https://github.com/xychelsea/deepfacelab-docker 
cd deepfacelab-docker/
docker build -t deepfacelab:latest-gpu-jupyter -f Dockerfile.nvidia-jupyter .

and I get:
...

Cloning into '/usr/local/deepfacelab'...
Updating files: 100% (203/203), done.
Removing intermediate container a233826f65dc
 ---> 3f3dc3e8728d
Step 17/22 : USER root
 ---> Running in 566a3149f694
Removing intermediate container 566a3149f694
 ---> 434e98af705f
Step 18/22 : RUN fix-permissions ${DEEPFACELAB_WORKSPACE}     && chmod +x ${DEEPFACELAB_SCRIPTS}/*.sh     && fix-permissions ${DEEPFACELAB_SCRIPTS}     && ln -s ${DEEPFACELAB_PATH} ${HOME}/deepfacelab     && ln -s ${DEEPFACELAB_WORKSPACE} ${HOME}/workspace     && ln -s ${DEEPFACELAB_SCRIPTS} ${HOME}/scripts
 ---> Running in 1aa3a05f6ebb
chmod: cannot access '/usr/local/deepfacelab/scripts/*.sh': No such file or directory
The command '/bin/bash -o pipefail -c fix-permissions ${DEEPFACELAB_WORKSPACE}     && chmod +x ${DEEPFACELAB_SCRIPTS}/*.sh     && fix-permissions ${DEEPFACELAB_SCRIPTS}     && ln -s ${DEEPFACELAB_PATH} ${HOME}/deepfacelab     && ln -s ${DEEPFACELAB_WORKSPACE} ${HOME}/workspace     && ln -s ${DEEPFACELAB_SCRIPTS} ${HOME}/scripts' returned a non-zero code: 1

**Comment by xychelsea** [comment]
Ah yes -- im sorry -- it wont work the codebase is completely borked right now -- let me update this as soon as possible, i will be streaming tonight on twitch

**Comment by xychelsea** [comment]
SEE NEW RELEASE (TESTING) https://github.com/xychelsea/deepfacelab-docker/releases/tag/v0.1.3

**Comment by seaniedan** [comment]
Thank you xychelsea - very appreciative of your efforts.
