### ISSUE TITLE
How to change defaults

### ISSUE THREAD

**Issue by seaniedan** [xychelsea/deepfacelab-docker#3]
In the read me, it says I can change the defaults:
ANACONDA_GID=100
ANACONDA_PATH=/usr/local/anaconda3
ANACONDA_UID=1000
ANACONDA_USER=anaconda

Where do I change these? Also, if I change the GID and UID to match the user on the bare metal running the container, will this solve the problem of root owning files produced from the docker container?

**Comment by xychelsea** [comment]
I'm pushing a major release change in a few hours -- you can change the defaults but i would recommend you leave them the same unless you want the GID and UID -- the problem is that the code base has not kept up with the latest release of DeepFaceLab, but i am fully updating this literally right now

**Comment by seaniedan** [comment]
Massively appreciate this work, xyChelsea. Just wondering -where- I would change those?

**Comment by xychelsea** [comment]
its all good, just neglected to update stuff from last summer's project -- so if you change them at the top of the Dockerfile like in the same manner as the ARG and ENVs in the anaconda3 docker container that would work -- i think you could just add them as ARGs and ENVs and it populate

**Comment by xychelsea** [comment]
Testing the new v0.1.3 dockerfiles at this very moment -- ill probably be posting them within the hour

**Comment by xychelsea** [comment]
https://github.com/xychelsea/anaconda3-docker is the dockerfiles with the alterable variables -- i will add these to the top of these in the 0.1.4 version perhaps, not this one though since it takes hours to build these containers

**Comment by seaniedan** [comment]
Oh yes, that makes sense. Thank you! I’ll test and close this issue when confirmed.

**Comment by xychelsea** [comment]
Okay, so you can actually create an environment file for docker-compose (but i dont think this works for NVIDIA) or send the environment variables direct to the container in the manner [described here](https://stackoverflow.com/questions/30494050/how-do-i-pass-environment-variables-to-docker-containers) -- v0.1.3 is now pushed and can be downloaded via

`git clone git://github.com/xychelsea/deepfacelab-docker.git`

SEE NEW RELEASE (TESTING) https://github.com/xychelsea/deepfacelab-docker/releases/tag/v0.1.3

**Comment by seaniedan** [comment]
In v0.1.3, I tried to change my envs after building a Docker container with the defaults, by using:
docker run --gpus all --rm -it -d     -v workspace:/usr/local/deepfacelab/workspace  -e ANACONDA_GID=20001 -e ANACONDA_UID=21040   deepfacelab:latest-gpu
...I must be fundamentally misunderstanding something, because I only get a token, like
d21aa890152af6ad81e267c8dae1f6bfc178fdb7ff3c25ec79766c1fb66cf756 and no bash shell. So I use 
docker exec -it my_container bash
to get a shell, then run
id
which gives me:
uid=1000(anaconda) gid=100(users) groups=100(users)
...which doesn't correspond with the envs I tried to pass.
Outside the container it give me a 'workspace' directory (empty) owned by root.

I'll try building the container again, changing the envs at the top of the script instead.

EDIT:I was using '-d' which starts the Docker in detatched mode. Not doing this, and following your instructions, gives a shell as expected.

**Comment by seaniedan** [comment]
Changing the UID and GID in the Dockerfile failed. I added:
ENV ANACONDA_GID=20001
ENV ANACONDA_UID=21040 

 I got: 

```
NotWritableError: The current user does not have write permissions to a required path.
  path: /usr/local/anaconda3/pkgs/urls.txt
  uid: 21040
  gid: 0

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 21040:0 /usr/local/anaconda3/pkgs/urls.txt

In general, it's not advisable to use 'sudo conda'.


The command '/bin/bash -o pipefail -c conda update -c defaults conda' returned a non-zero code: 1
```

**Comment by seaniedan** [comment]
Additional info.... to solve the issue of root owning all the files outside of a container, I would usually run with --user "$(id -u):$(id -g)" before the image name, e.g.:

```
docker run --rm -it \
    -v workspace:/usr/local/deepfacelab/workspace \
    --user "$(id -u):$(id -g)" \
    xychelsea/deepfacelab:latest
```
..however, in this repo, the 'workspace' directory is always owned by root. 
Maybe it's something to do with the line     `&& mkdir -p ${DEEPFACELAB_WORKSPACE} \` in the dockerfile, which is making that file as the anacona user.
