### ISSUE TITLE
jupyter notebook not running in deepfacelab-docker-0.1.3

### ISSUE THREAD

**Issue by seaniedan** [xychelsea/deepfacelab-docker#4]
Maybe I don't know what I'm doing, but I downloaded and unzipped deepfacelab-docker-0.1.3 
inside that folder I ran
**docker build -t deepfacelab:latest-gpu-jupyter -f Dockerfile.nvidia-jupyter .**
After a few cups of tea, I got:
**Successfully tagged deepfacelab:latest-gpu-jupyter**
I then ran
docker run --gpus all --rm -it -d     -v workspace:/usr/local/deepfacelab/workspace     -p 8888:8888     deepfacelab:latest-gpu-jupyter
..and I see a token
When I go to http://0.0.0.0:8888/ I see no notebook. I run:
docker exec -it <MY_CONTAINER> jupyter notebook list
and get:
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"jupyter\": executable file not found in $PATH": unknown

..this is new, in previous versions of this docker repo, I could get the token and jupyter notebook ran.

**Comment by xychelsea** [comment]
Oh noes, now Jupyter is borked -- got it -- thats a deeper issue -- i recommend using the non Jupyter version for now

**Comment by seaniedan** [comment]
Thankyou for the quick reply. I’m really confused how to get started with this docker image. I don’t get a shell with the Nvidia only version. EDIT: Didn't get a shell because I was still using '-d' which was not needed.

**Comment by xychelsea** [comment]
ok -- so jupyter notebooks is getting replaced with jupyter labs so i gotta update the whole stack now to v0.1.4 :( ill work on this soon i need it for a project i wanna work on soon
