### ISSUE TITLE
ModuleNotFoundError: No module named 'ffmpeg'

### ISSUE THREAD

**Issue by seaniedan** [xychelsea/deepfacelab-docker#6]
My love-hate relationship with ffmpeg continues! 

I build the container with the downloaded and unzipped deepfacelab-docker-0.1.3
inside that folder I ran
docker build -t deepfacelab:latest-gpu-jupyter -f Dockerfile.nvidia .
After a really decadent cup of Yorkshire Gold (one sugar, no milk, thanks), I got:
Successfully tagged deepfacelab:latest-gpu

I didn't see any discernable errors regarding ffmpeg. However, inside the container, I cd to the scripts directory and try to run:

```
(deepfacelab) anaconda@aaab3d68ee7e:~/scripts$ ./2_extract_PNG_from_video_data_src.sh 
Traceback (most recent call last):
  File "/usr/local/deepfacelab/main.py", line 324, in <module>
    arguments.func(arguments)
  File "/usr/local/deepfacelab/main.py", line 181, in process_videoed_extract_video
    from mainscripts import VideoEd
  File "/usr/local/deepfacelab/mainscripts/VideoEd.py", line 3, in <module>
    import ffmpeg
ModuleNotFoundError: No module named 'ffmpeg'
```
I wonder if the hard work you've done in compiling ffmpeg has broken a python library? 
`(deepfacelab) anaconda@aaab3d68ee7e:~/scripts$ which ffmpeg
`
reports it exists in Bash world:
`/usr/local/ffmpeg-nvenc/bin/ffmpeg`

**Comment by seaniedan** [comment]
running 
`conda install -c conda-forge ffmpeg-python
`
inside the container fixed the issue. Now I need to figure out how to approach this in the Dockerfile.

**Comment by seaniedan** [comment]
This error can be fixed by adding the line
        ffmpeg-python \
in the dockerfile after the line
RUN conda create -c conda-forge -n deepfacelab \

Will attempt a pull request shortly.

**Comment by xychelsea** [comment]
Great thanks :D ffmpeg needs to be compiled tho for NVIDIA :(

**Comment by seaniedan** [comment]
Seemed to work for me.. but maybe this is not working and masked by my other issues. What's the solution, Chelsea? You're compiling FFPMEG in the container, but not ffmpeg-python? Is this something you can fix?
