### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by seaniedan** [xychelsea/deepfacelab-docker#9]
That old missing tensorflow problem. Bit stumped by this one. I ran:
```
(deepfacelab) anaconda@554ac43cdd60:~/scripts$ ./4_data_src_extract_faces_S3FD.sh
[wf] Face type ( f/wf/head ?:help ) : ?
Full face / whole face / head. 'Whole face' covers full area of face include forehead. 'head' covers full head, but requires XSeg for src and dst faceset.
[wf] Face type ( f/wf/head ?:help ) : head
head
[0] Max number of faces from image ( ?:help ) : ?
If you extract a src faceset that has frames with a large number of faces, it is advisable to set max faces to 3 to speed up extraction. 0 - unlimited
[0] Max number of faces from image ( ?:help ) : 1
1
[768] Image size ( 256-2048 ?:help ) : ?
Output image size. The higher image size, the worse face-enhancer works. Use higher than 512 value only if the source image is sharp enough and the face does not need to be enhanced.
[768] Image size ( 256-2048 ?:help ) : 512
512
[90] Jpeg quality ( 1-100 ?:help ) : 90
90
[n] Write debug images to aligned_debug? ( y/n ) : y
Extracting faces...
Error while subprocess initialization: Traceback (most recent call last):
  File "/usr/local/deepfacelab/core/joblib/SubprocessorBase.py", line 62, in _subprocess_run
    self.on_initialize(client_dict)
  File "/usr/local/deepfacelab/mainscripts/Extractor.py", line 68, in on_initialize
    nn.initialize (device_config)
  File "/usr/local/deepfacelab/core/leras/nn.py", line 79, in initialize
    import tensorflow
ModuleNotFoundError: No module named 'tensorflow'

```
Not sure how to proceed. Any help welcomed!

**Comment by xychelsea** [comment]
Redoing the entire Anaconda / TF stack in the next day with help from a containerizing expert to speed things up

**Comment by xychelsea** [comment]
Okay -- first, you need to make sure that you have [nvidia docker](https://github.com/NVIDIA/nvidia-docker) installed on the host system if you're going to use the graphics card -- once it is installed and running use:

```
docker run --rm --gpus all nvidia/cuda:11.2.0-devel-ubuntu20.04 nvidia-smi
```

to test to ensure that the docker container is working and can see the host system's GPU card via PCI

finally, run a bash file like this (change the directory from the default first) to run the docker container on your system

```bash
#!/bin/bash

DEEPFACELAB_NAME=deepfacelab
DEEPFACELAB_WORKSPACE=~/docker/deepfacelab
DEEPFACELAB_MOUNT=/usr/local/deepfacelab/workspace
DEEPFACELAB_PORT=8888

docker run \
	--detach \
	--gpus all \
	--interactive \
	--name $DEEPFACELAB_NAME \
	--publish $DEEPFACELAB_PORT:8888 \
	--rm \
	--tty \
	--volume $DEEPFACELAB_WORKSPACE:$DEEPFACELAB_MOUNT \
	xychelsea/deepfacelab:v0.2-gpu-jupyter
```

This should finally run -- it all runs locally here

**Comment by seaniedan** [comment]
This is great - I have some thoughts for improvement - e.g. could you  
`RUN jupyter notebook list
`
at the end of the dockerfile, to display the address and token to us 'noobs'. I could try and write some documentation for you if you'd like? 

Happy St. David's Day, if you're into that sort of thing.

**Comment by seaniedan** [comment]
Also, just to confirm, nvidia docker is installed on the host system and all working fine.

**Comment by xychelsea** [comment]
Thank you for your patience and persistence -- these errors really help me figure out how to make this better -- im going to dry run deepfacelab and see if i can replicate now -- i think its just incompatible packages between the debian and conda repositories but i i wont know until i break it myself

**Comment by xychelsea** [comment]
Ok, I think I've finally figured it out. Thank you again. I will be updating v0.2 in a few hours -- just remove the old container and redownload v0.2
